# Generated by Django 3.1.4 on 2021-05-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='joindetail',
        ),
    ]
