# Generated by Django 3.1.4 on 2021-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_remove_information_joindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='join',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
