# Generated by Django 3.1.4 on 2021-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_auto_20210109_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
