# Generated by Django 3.1.4 on 2021-01-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
