# Generated by Django 3.1.4 on 2021-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='artwork_rating',
            field=models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'fine'), (4, 'good'), (5, 'excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='website_rating',
            field=models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'fine'), (4, 'good'), (5, 'excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='youtube_rating',
            field=models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'fine'), (4, 'good'), (5, 'excellent')]),
        ),
    ]
